---
ssl: false
lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  - pattern : kafka.server<type=ReplicaManager, name=(.+)><>(Value|OneMinuteRate)
    name: "kafka_server_replicamanager_$1"
  - pattern : kafka.controller<type=KafkaController, name=(.+)><>Value
    name: "kafka_controller_kafkacontroller_$1"
  - pattern : kafka.server<type=BrokerTopicMetrics, name=(.+)><>OneMinuteRate
    name: "kafka_server_brokertopicmetrics_$1"
  - pattern : kafka.network<type=RequestMetrics, name=RequestsPerSec, request=(.+)><>OneMinuteRate
    name: "kafka_network_requestmetrics_requestspersec_$1"
  - pattern : kafka.network<type=SocketServer, name=NetworkProcessorAvgIdlePercent><>Value
    name: "kafka_network_socketserver_networkprocessoravgidlepercent"
  - pattern : kafka.server<type=ReplicaFetcherManager, name=MaxLag, clientId=(.+)><>Value
    name: "kafka_server_replicafetchermanager_maxlag_$1"
  - pattern : kafka.server<type=KafkaRequestHandlerPool, name=RequestHandlerAvgIdlePercent><>OneMinuteRate
    name: "kafka_kafkarequesthandlerpool_requesthandleravgidlepercent"
  - pattern : kafka.controller<type=ControllerStats, name=(.+)><>OneMinuteRate
    name: "kafka_controller_controllerstats_$1"
  - pattern : kafka.server<type=SessionExpireListener, name=(.+)><>OneMinuteRate
    name: "kafka_server_sessionexpirelistener_$1"
  - pattern : kafka.server<type=Produce, (?:user=([-.\w]+))?(?:,)?(?:client-id=([-.\w]+))?><>(\w+)
